object FSmiles: TFSmiles
  Left = 82
  Top = 291
  BiDiMode = bdLeftToRight
  BorderStyle = bsNone
  Caption = 'Smiles'
  ClientHeight = 271
  ClientWidth = 387
  Color = clBtnFace
  Font.Charset = RUSSIAN_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Arial'
  Font.Style = [fsBold]
  FormStyle = fsStayOnTop
  KeyPreview = True
  OldCreateOrder = False
  ParentBiDiMode = False
  Position = poDefault
  OnCreate = FormCreate
  OnHide = FormHide
  OnKeyDown = FormKeyDown
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 16
  object MenuSmilesBox: TPaintBox
    Left = 0
    Top = 0
    Width = 387
    Height = 271
    Align = alClient
    Color = clMenu
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = []
    ParentColor = False
    ParentFont = False
    OnClick = MenuSmilesBoxClick
    OnMouseMove = MenuSmilesBoxMouseMove
    OnMouseUp = MenuSmilesBoxMouseUp
    OnPaint = MenuSmilesBoxPaint
  end
  object UpdTmr: TTimer
    Interval = 40
    OnTimer = UpdTmrTimer
    Left = 24
    Top = 16
  end
end
